#! /usr/bin/env sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on

picom &
polybar example &

feh --bg-scale ~/sync/pictures_s/wallpapers/fon1.jpg
