#! /usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 4
bspc config focused_border_color "#ff6600"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Yad state=floating

xset r rate 200 30

picom &
polybar example &
dunst &

wallpaper="$HOME/.tiling-config/wallpapers/wp1.jpg"
feh --no-fehbg --bg-scale "$wallpaper"

# wallpaper="$HOME/.tiling-config/wallpapers/live_wp1.mp4"
#
# if ! pidof mpv > /dev/null; then
# 	xwinwrap -ov -g 1920x1080+0+0 -- \
# 		mpv --no-audio --loop --panscan=1 --no-osc --no-input-default-bindings \
# 			--hwdec=auto-safe --vo=gpu --profile=low-latency --wid=%WID "$wallpaper"
# fi
