#! /usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 4
bspc config focused_border_color "#ff6600"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Yad state=floating

picom &
polybar example &

wallpaper="$HOME/sync/pictures_s/wallpapers/fon1.jpg"
feh --no-fehbg --bg-scale "$wallpaper"
